### ISSUE TITLE
All tags serializer

### ISSUE THREAD

**Issue by afk-mario** [glemmaPaul/django-taggit-serializer#24]
Is there a serializer for the tags itself, not a tag field ?
Currently I have:

```
from taggit.models                 import Tag
class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tag
        fields = ('name',)
```

**Comment by glemmaPaul** [comment]
Hey @Arlefreak I think this question could better be asked here: https://github.com/alex/django-taggit

But to not leave you unhanded, this looks like it could work. You should then attach this to the other serializer.
