### ISSUE TITLE
'list' object has no attribute 'set'

### ISSUE THREAD

**Issue by cristiangrojas** [glemmaPaul/django-taggit-serializer#27]
This code `getattr(tag_object, key)` inside "_save_tags" method is returning a list instead of a TaggableManager class.

I had to do it this way to get it working in my project:

```
def _save_tags(self, tag_object, tags):
        # Had to override because tag_object.tags is returning a list
        for key in tags.keys():
            tag_values = tags.get(key)
            Photo.objects.get(id=tag_object.id).tags.set(*tag_values)

        return tag_object
```

**Comment by glemmaPaul** [comment]
@cristiangrojas Thanks for reporting the issue! I've tried to replicate it, but could not find out what was going wrong, could you tell me if this was during saving or updating the object?

**Comment by glemmaPaul** [comment]
@cristiangrojas Sorry but I have to close this issue as I haven't got a response, if you want you could still respond 👍
