### ISSUE TITLE
pypi version is out of date

### ISSUE THREAD

**Issue by longhotsummer** [glemmaPaul/django-taggit-serializer#4]
Hi, great little package, very useful. The version on pypi claims to be 0.1.1 but is missing at least from 5c62cb01895af4c410c0bc7132b36c6a4d77a9a4 onwards. Could you update pypi and/or bump the version number?

I needed to add the `child` param to my field which shouldn't be required as far as I can tell.

``` python
tags = TagListSerializerField(child=serializers.CharField())
```

Thanks!

**Comment by glemmaPaul** [comment]
Thanks for pointing this out! I'm going to resolve it all!
