### ISSUE TITLE
Saving tags give me an expected response, but nothing is actually saved into the database

### ISSUE THREAD

**Issue by oliver-zhou** [glemmaPaul/django-taggit-serializer#40]
Using Django==1.11.9, django-taggit==0.22.2, and django-taggit-serializer==0.1.5

When doing a 'PATCH' to a model with tags, the response reflects the new tags, but on a subsequent 'GET', the tags do not seem to have been updated.

tags": [
        "test tag 1",
        "test tag 2",
    ],

Manually doing an add() works fine via the shell

```
In [6]: model_with_tags.tags.add('test')

In [7]: model_with_tags.tags.all()
Out[7]: <QuerySet [<Tag: asdf>, <Tag: asdfzxcv>, <Tag: test>]>

```

**Comment by lucabezerra** [comment]
@oliver-zhou Can you share some of your code? The model and the serializer, maybe?
I'm also having this problem, but it was after a code refactor, so it might or might not be related, haha. Maybe I can help you (and it will be easier for people in this repo as well) if you show some of your code :)

**Comment by oliver-zhou** [comment]
@lucabezerra Actually, forget everything I wrote. My issue actually boiled down to not properly adding the TaggitSerializer to my own Model's Serializer, and then needing to do a GenericUUIDTaggedItemBase since my model used UUIDs and not Integer PKs, as per https://django-taggit.readthedocs.io/en/latest/custom_tagging.html
