### ISSUE TITLE
Getting KeyError on partial update (PATCH) when 'tags' not included

### ISSUE THREAD

**Issue by joeweiss** [glemmaPaul/django-taggit-serializer#7]
Partials update (via PATCH request) is throwing a KeyError in [_pop_tags](https://github.com/glemmaPaul/django-taggit-serializer/blob/master/taggit_serializer/serializers.py#L48) when the 'tags' field's data is not included in the patch request.  

In our situation, we patch a lot of records, and we only patch the fields that change.

**Current implementation**

``` python
    def _pop_tags(self, validated_data):
        to_be_tagged = {}

        for key in self.fields.keys():
            field = self.fields[key]
            if isinstance(field, TagListSerializerField):
                to_be_tagged[key] = validated_data.pop(key)

        return (to_be_tagged, validated_data)
```

We need the check the existence of the key before pop'ing it, correct?

``` python
    def _pop_tags(self, validated_data):
        to_be_tagged = {}

        for key in self.fields.keys():
            field = self.fields[key]
            if isinstance(field, TagListSerializerField):
                if key in validated_data:
                    to_be_tagged[key] = validated_data.pop(key)

        return (to_be_tagged, validated_data)
```

I'm happy to open a PR, but wanted to make sure I wasn't missing something simple or overthinking it.

**Comment by glemmaPaul** [comment]
Yeah you're absolutely right! It's strange I've never added `partial=True`. I'll add tests for that too. You can open a PR if you would like, thank you for bringing it up :+1:

**Comment by joeweiss** [comment]
Great. I opened a PR. It needs tests though. Wasn't sure how you wanted those handled.

**Comment by joeweiss** [comment]
Hey folks. This issue is occurring again.

It looks like the fix for this issue was overwritten after the PR was accepted.

Here's where it happened:
https://github.com/glemmaPaul/django-taggit-serializer/commit/2909a7fa62b0fec94ff94a8b657e9afea9fb0379#diff-332a5a3794e86d0e4a5433137ec60215L48

I'm opening another PR now. Thanks!
